/**
 * Spanish translation layer for Sentiment AI outputs.
 * The Modal agent returns results in English — this module
 * translates intent_signals, risk_flags, recommended_action,
 * and reasoning to Spanish before display.
 */

const INTENT_SIGNAL_MAP: Record<string, string> = {
  "high_purchase_intent": "Alta intención de compra",
  "budget_ready": "Presupuesto listo",
  "active_comparison": "Comparando activamente",
  "repeat_customer": "Cliente recurrente",
  "referral_potential": "Potencial de referido",
  "upsell_opportunity": "Oportunidad de upsell",
  "cross_sell_opportunity": "Oportunidad de cross-sell",
  "decision_maker": "Tomador de decisiones",
  "timeline_urgency": "Urgencia de tiempo",
  "project_defined": "Proyecto definido",
  "design_interest": "Interés en diseño",
  "showroom_visit": "Visita a showroom",
  "price_sensitive": "Sensible al precio",
  "brand_loyal": "Leal a la marca",
  "multiple_touchpoints": "Múltiples puntos de contacto",
  "engaged_recently": "Interacción reciente",
  "requesting_quote": "Solicitando cotización",
  "ready_to_close": "Listo para cerrar",
  "needs_follow_up": "Necesita seguimiento",
  "warm_lead": "Lead tibio",
  "hot_lead": "Lead caliente",
};

const RISK_FLAG_MAP: Record<string, string> = {
  "no_response": "Sin respuesta",
  "long_inactive": "Inactivo prolongado",
  "price_objection": "Objeción de precio",
  "competitor_risk": "Riesgo de competencia",
  "budget_mismatch": "Presupuesto no coincide",
  "declining_engagement": "Engagement decreciente",
  "negative_sentiment": "Sentimiento negativo",
  "unresponsive": "No responde",
  "delayed_decision": "Decisión retrasada",
  "lost_interest": "Perdió interés",
  "poor_fit": "Mal ajuste",
  "communication_gap": "Brecha de comunicación",
  "stale_lead": "Lead estancado",
  "high_churn_risk": "Alto riesgo de abandono",
  "duplicate_lead": "Lead duplicado",
  "wrong_contact": "Contacto incorrecto",
  "timeline_mismatch": "Timeline no coincide",
  "no_budget": "Sin presupuesto",
  "ghosting": "Sin contacto (ghosting)",
  "complaint": "Queja registrada",
};

// Common English → Spanish phrase translations for reasoning/actions.
// Multi-word phrases MUST come before single-word entries so they match first.
const PHRASE_TRANSLATIONS: [RegExp, string][] = [
  // ── Multi-word phrases (order matters) ──
  [/\bclose the deal\b/gi, "cerrar el negocio"],
  [/\bfollow up\b/gi, "dar seguimiento"],
  [/\bfollow-up\b/gi, "seguimiento"],
  [/\bschedule a call\b/gi, "programar una llamada"],
  [/\bsend an email\b/gi, "enviar un correo"],
  [/\bsend a message\b/gi, "enviar un mensaje"],
  [/\bno response\b/gi, "sin respuesta"],
  [/\bno activity\b/gi, "sin actividad"],
  [/\bhigh engagement\b/gi, "alto engagement"],
  [/\blow engagement\b/gi, "bajo engagement"],
  [/\bthe lead\b/gi, "el lead"],
  [/\bthis lead\b/gi, "este lead"],
  [/\bhas shown\b/gi, "ha mostrado"],
  [/\bhas not\b/gi, "no ha"],
  [/\bshould be\b/gi, "debería ser"],
  [/\bneeds to be\b/gi, "necesita ser"],
  [/\bwe recommend\b/gi, "recomendamos"],
  [/\bI recommend\b/gi, "recomiendo"],
  [/\bstrong interest\b/gi, "fuerte interés"],
  [/\bweak interest\b/gi, "interés débil"],
  [/\bbased on\b/gi, "basado en"],
  [/\bdue to\b/gi, "debido a"],
  [/\bin order to\b/gi, "para"],
  [/\bloss reasons?\b/gi, "razones de pérdida"],
  [/\bre-engage\b/gi, "re-contactar"],
  [/\bre engage\b/gi, "re-contactar"],
  [/\bmixed signals?\b/gi, "señales mixtas"],
  [/\blow conversion potential\b/gi, "bajo potencial de conversión"],
  [/\bhigh conversion potential\b/gi, "alto potencial de conversión"],
  [/\bconversion potential\b/gi, "potencial de conversión"],
  [/\bminimal messaging\b/gi, "mensajería mínima"],
  [/\bshowroom visit\b/gi, "visita a showroom"],
  [/\binvestigate\b/gi, "investigar"],
  [/\bqualification\b/gi, "calificación"],
  [/\bvia WhatsApp\b/gi, "por WhatsApp"],
  [/\bvia email\b/gi, "por correo"],
  [/\bvia phone\b/gi, "por teléfono"],
  [/\band re-engage\b/gi, "y re-contactar"],
  [/\band\b/gi, "y"],
  [/\bbut\b/gi, "pero"],

  // ── Single-word entries ──
  [/\brecommend\b/gi, "recomendar"],
  [/\bimmediately\b/gi, "inmediatamente"],
  [/\burgent\b/gi, "urgente"],
  [/\bpriority\b/gi, "prioridad"],
  [/\bcustomer\b/gi, "cliente"],
  [/\bprospect\b/gi, "prospecto"],
  [/\bconversion\b/gi, "conversión"],
  [/\bretention\b/gi, "retención"],
  [/\bchurn\b/gi, "abandono"],
  [/\bpositive\b/gi, "positivo"],
  [/\bnegative\b/gi, "negativo"],
  [/\bneutral\b/gi, "neutral"],
  [/\bengagement\b/gi, "engagement"],
  [/\binteraction\b/gi, "interacción"],
  [/\binteractions\b/gi, "interacciones"],
  [/\bpurchase\b/gi, "compra"],
  [/\bbudget\b/gi, "presupuesto"],
  [/\bdesign\b/gi, "diseño"],
  [/\bkitchen\b/gi, "cocina"],
  [/\bcloset\b/gi, "closet"],
  [/\bbathroom\b/gi, "baño"],
  [/\bproject\b/gi, "proyecto"],
  [/\bshowroom\b/gi, "showroom"],
  [/\bquote\b/gi, "cotización"],
  [/\bdeal\b/gi, "negocio"],
  [/\bactive\b/gi, "activo"],
  [/\binactive\b/gi, "inactivo"],
  [/\brecent\b/gi, "reciente"],
  [/\boverall\b/gi, "en general"],
  [/\bhowever\b/gi, "sin embargo"],
  [/\btherefore\b/gi, "por lo tanto"],
  [/\balthough\b/gi, "aunque"],
  [/\bwhich\b/gi, "el cual"],
  [/\bindicate\b/gi, "indica"],
  [/\bindicates?\b/gi, "indica"],
  [/\bpotential\b/gi, "potencial"],
  [/\bdepth\b/gi, "profundidad"],
  [/\bmessaging\b/gi, "mensajería"],
  [/\blost\b/gi, "perdido"],
  [/\bwon\b/gi, "ganado"],
  [/\bopen\b/gi, "abierto"],
  [/\bclosed\b/gi, "cerrado"],
  [/\breasons?\b/gi, "razones"],
  [/\bsignals?\b/gi, "señales"],
  [/\bvisit\b/gi, "visita"],
  [/\bminimal\b/gi, "mínimo"],
  [/\bcontact\b/gi, "contacto"],
  [/\bresponse\b/gi, "respuesta"],
  [/\bscoring\b/gi, "puntuación"],
  [/\bscore\b/gi, "puntaje"],
  [/\bhistory\b/gi, "historial"],
  [/\banalysis\b/gi, "análisis"],
  [/\bopportunity\b/gi, "oportunidad"],
  [/\bopportunities\b/gi, "oportunidades"],
  [/\bimprove\b/gi, "mejorar"],
  [/\bincrease\b/gi, "aumentar"],
  [/\bdecrease\b/gi, "disminuir"],
  [/\bmaintain\b/gi, "mantener"],
  [/\bmonitor\b/gi, "monitorear"],
  [/\btrack\b/gi, "rastrear"],
  [/\bpersonalized\b/gi, "personalizado"],
  [/\bpersonalize\b/gi, "personalizar"],
  [/\boffer\b/gi, "oferta"],
  [/\bdiscount\b/gi, "descuento"],
  [/\bpromotion\b/gi, "promoción"],
  [/\bcampaign\b/gi, "campaña"],
  [/\bstrategy\b/gi, "estrategia"],
  [/\bapproach\b/gi, "enfoque"],
  [/\btarget\b/gi, "objetivo"],
  [/\bachieve\b/gi, "lograr"],
  [/\bsuccess\b/gi, "éxito"],
  [/\bfailure\b/gi, "fracaso"],
  [/\brisk\b/gi, "riesgo"],
  [/\bhigh\b/gi, "alto"],
  [/\blow\b/gi, "bajo"],
  [/\bmedium\b/gi, "medio"],
  [/\bstrong\b/gi, "fuerte"],
  [/\bweak\b/gi, "débil"],
  [/\bcurrent\b/gi, "actual"],
  [/\bprevious\b/gi, "anterior"],
  [/\bnext\b/gi, "siguiente"],
  [/\bstep\b/gi, "paso"],
  [/\baction\b/gi, "acción"],
  [/\bresult\b/gi, "resultado"],
  [/\bresults\b/gi, "resultados"],
  [/\bdata\b/gi, "datos"],
  [/\binformation\b/gi, "información"],
  [/\bdetails\b/gi, "detalles"],
  [/\bsummary\b/gi, "resumen"],
  [/\breport\b/gi, "reporte"],
  [/\bstatus\b/gi, "estado"],
  [/\bprogress\b/gi, "progreso"],
  [/\bcomplete\b/gi, "completo"],
  [/\bincomplete\b/gi, "incompleto"],
  [/\bpending\b/gi, "pendiente"],
  [/\boverdue\b/gi, "vencido"],
  [/\bscheduled\b/gi, "programado"],
  [/\bconfirmed\b/gi, "confirmado"],
  [/\bcancelled\b/gi, "cancelado"],
  [/\brejected\b/gi, "rechazado"],
  [/\baccepted\b/gi, "aceptado"],
  [/\bapproved\b/gi, "aprobado"],
  [/\bdenied\b/gi, "denegado"],
  [/\bwaiting\b/gi, "esperando"],
  [/\bprocessing\b/gi, "procesando"],
  [/\bdelivered\b/gi, "entregado"],
  [/\bsent\b/gi, "enviado"],
  [/\breceived\b/gi, "recibido"],
  [/\bread\b/gi, "leído"],
  [/\bunread\b/gi, "no leído"],
  [/\bclicked\b/gi, "cliqueado"],
  [/\bopened\b/gi, "abierto"],
  [/\binterested\b/gi, "interesado"],
  [/\bnot interested\b/gi, "no interesado"],
  [/\bqualified\b/gi, "calificado"],
  [/\bunqualified\b/gi, "no calificado"],
  [/\bcontacted\b/gi, "contactado"],
  [/\bfollowed\b/gi, "seguido"],
  [/\bupdated\b/gi, "actualizado"],
  [/\bcreated\b/gi, "creado"],
  [/\bdeleted\b/gi, "eliminado"],
  [/\bmodified\b/gi, "modificado"],
  [/\bchanged\b/gi, "cambiado"],
  [/\badded\b/gi, "agregado"],
  [/\bremoved\b/gi, "eliminado"],
  [/\bnew\b/gi, "nuevo"],
  [/\bold\b/gi, "antiguo"],
  [/\bexisting\b/gi, "existente"],
  [/\bavailable\b/gi, "disponible"],
  [/\bunavailable\b/gi, "no disponible"],
  [/\brequired\b/gi, "requerido"],
  [/\boptional\b/gi, "opcional"],
  [/\bimportant\b/gi, "importante"],
  [/\bcritical\b/gi, "crítico"],
  [/\bnormal\b/gi, "normal"],
  [/\bspecial\b/gi, "especial"],
  [/\bcustom\b/gi, "personalizado"],
  [/\bdefault\b/gi, "predeterminado"],
  [/\benabled\b/gi, "habilitado"],
  [/\bdisabled\b/gi, "deshabilitado"],
  [/\bsuccessful\b/gi, "exitoso"],
  [/\bfailed\b/gi, "fallido"],
  [/\berror\b/gi, "error"],
  [/\bwarning\b/gi, "advertencia"],
  [/\bnotice\b/gi, "aviso"],
  [/\balert\b/gi, "alerta"],
  [/\bmessage\b/gi, "mensaje"],
  [/\bmessages\b/gi, "mensajes"],
  [/\bcall\b/gi, "llamada"],
  [/\bcalls\b/gi, "llamadas"],
  [/\bmeeting\b/gi, "reunión"],
  [/\bmeetings\b/gi, "reuniones"],
  [/\btask\b/gi, "tarea"],
  [/\btasks\b/gi, "tareas"],
  [/\bnote\b/gi, "nota"],
  [/\bnotes\b/gi, "notas"],
  [/\bcomment\b/gi, "comentario"],
  [/\bcomments\b/gi, "comentarios"],
  [/\bfeedback\b/gi, "retroalimentación"],
  [/\breview\b/gi, "revisión"],
  [/\bsurvey\b/gi, "encuesta"],
  [/\bform\b/gi, "formulario"],
  [/\bwebsite\b/gi, "sitio web"],
  [/\bpage\b/gi, "página"],
  [/\blink\b/gi, "enlace"],
  [/\bimage\b/gi, "imagen"],
  [/\bfile\b/gi, "archivo"],
  [/\bdocument\b/gi, "documento"],
  [/\bfolder\b/gi, "carpeta"],
  [/\bcategory\b/gi, "categoría"],
  [/\btag\b/gi, "etiqueta"],
  [/\blabel\b/gi, "etiqueta"],
  [/\bname\b/gi, "nombre"],
  [/\btitle\b/gi, "título"],
  [/\bdescription\b/gi, "descripción"],
  [/\btype\b/gi, "tipo"],
  [/\bvalue\b/gi, "valor"],
  [/\bamount\b/gi, "monto"],
  [/\bprice\b/gi, "precio"],
  [/\bcost\b/gi, "costo"],
  [/\btotal\b/gi, "total"],
  [/\baverage\b/gi, "promedio"],
  [/\bmaximum\b/gi, "máximo"],
  [/\bminimum\b/gi, "mínimo"],
  [/\bcount\b/gi, "cantidad"],
  [/\bpercentage\b/gi, "porcentaje"],
  [/\bratio\b/gi, "proporción"],
  [/\brate\b/gi, "tasa"],
  [/\btrend\b/gi, "tendencia"],
  [/\bgrowth\b/gi, "crecimiento"],
  [/\bdecline\b/gi, "declive"],
  [/\bstable\b/gi, "estable"],
  [/\bvolatile\b/gi, "volátil"],
  [/\bconsistent\b/gi, "consistente"],
  [/\binconsistent\b/gi, "inconsistente"],
  [/\breliable\b/gi, "confiable"],
  [/\bunreliable\b/gi, "no confiable"],
];

/**
 * Translate a known intent signal key to Spanish.
 */
export function translateIntentSignal(signal: string): string {
  return INTENT_SIGNAL_MAP[signal] ?? translateFreeText(signal);
}

/**
 * Translate a known risk flag key to Spanish.
 */
export function translateRiskFlag(flag: string): string {
  return RISK_FLAG_MAP[flag] ?? translateFreeText(flag);
}

/**
 * Best-effort translation of free-form English text to Spanish.
 * Applies known phrase replacements. Always runs — the AI agent often
 * returns mixed English/Spanish text so we cannot skip based on the
 * presence of Spanish words.
 */
export function translateFreeText(text: string): string {
  if (!text) return text;

  let result = text;
  for (const [pattern, replacement] of PHRASE_TRANSLATIONS) {
    result = result.replace(pattern, replacement);
  }

  // Replace underscores with spaces and capitalize
  result = result.replace(/_/g, " ");

  return result;
}

/**
 * Translate all translatable fields of a SentimentResult.
 */
export function translateSentimentResult<T extends {
  intent_signals: string[];
  risk_flags: string[];
  recommended_action: string;
  reasoning: string;
}>(result: T): T {
  return {
    ...result,
    intent_signals: result.intent_signals.map(translateIntentSignal),
    risk_flags: result.risk_flags.map(translateRiskFlag),
    recommended_action: translateFreeText(result.recommended_action),
    reasoning: translateFreeText(result.reasoning),
  };
}
